### PR TITLE
Update axe-core to 3.4.1

### PR DESCRIPTION
**Pull request by mohanraj-r**
axe-core 3.3.1 was released on Jul 24. There has been several bugfixes and features (90+ commits) since. Updating to the latest release of [3.4.1](https://github.com/dequelabs/axe-core/releases/tag/v3.4.1).

* Update package.json 
* Update jest snapshots to reflect changes in axe help URLs from 3.3 to 3.4

### CODE REVIEW

**Comment by mohanraj-r** [comment]
closes #76

**Comment by dominicfraser** [comment]
My team would also love to see this reviewed/merged @nickcolley :) 

It could even be bumped to `3.4.1` released 5 days ago on 18th Dec 2019 :)

**Comment by nickcolley** [comment]
Hey folks,

Thanks for the help and review, I'm currently on holiday but will get this sorted in the new year thanks for your patience. ♥️

**Comment by dominicfraser** [comment]
Thanks @nickcolley :)

**Comment by dominicfraser** [comment]
Morning @nickcolley - still eagerly waiting on this :) :)

**Comment by nickcolley** [comment]
@dominicfraser thanks for your patience, I've published this update as 3.3.0

**Comment by dominicfraser** [comment]
Thanks!

**Pull request merged**
