### PR TITLE
updated violation output to display a list of fixes for each node

### PR DESCRIPTION
**Pull request by dakebl**
This PR updates the console output on violations to include the list of suggested fixes for each affected node. This also adds some slight formatting changes.

image

Addresses #63

### CODE REVIEW

**Comment by dakebl** [comment]
What do you think @nickcolley?

**Comment by nickcolley** [comment]
I think when I originally put this together I intentionally did not output these as I thought it might be confusing to be given all these suggestions at once.

I felt that the guidance URL was a better place to send people.

However for examples with only one or two fixes this seems useful.

Sorry to be a bit of a broken record but could we consider doing this without the extra dependency?

I think we can still have this helpful output without the colour changes?

**Comment by dakebl** [comment]
Hey @nickcolley,

Sure thing, we can remove `chalk` if you like.
I felt that, in the same vain as yourself, the content was a lot to digest when presented as is, and so I thought that a color differential would be a good way to break it up. 

Could use ANSI escape codes instead to color them manually myself?
```js
const printCyan = text => console.log('\x1b[36m%s\x1b[0m', text);

printCyan(node.failureSummary);
```

Or some other sort of character based framing? Box framing?

Happy to remove and go as is. Let me know what you'd like to go with 🙌

**Comment by nickcolley** [comment]
Let's go with the extra dependency, we may want to highlight other things in the future, and I don't want to have to deal with cross platform bugs in terminals! :)

**Pull request merged**
