### PR TITLE
Update axe-core to 3.5.5

### PR DESCRIPTION
**Pull request by dominicfraser**
`axe-core` has released some patch version bug fixes we can take advantage of :) 

As these are patch versions the 'help' link captured in snapshots remains the same, so continue to pass.

https://github.com/dequelabs/axe-core/releases

### CODE REVIEW

**Comment by dominicfraser** [comment]
cc: @mohanraj-r

**Comment by mohanraj-r** [comment]
@dominicfraser they have just released v3.5.5 https://github.com/dequelabs/axe-core/releases/tag/v3.5.5
Would be good to update to that.

**Comment by dominicfraser** [comment]
> 2 hours ago

🚀

**Comment by dominicfraser** [comment]
@nickcolley @mohanraj-r - pushed 3.5.5

**Comment by nickcolley** [comment]
I've messed up in the past and published arguably breaking versions, since axe seems to change their rule set outside of major versions...

Could you check the release notes to see if there is any rule changes which could break people's snapshot tests for example please?

https://github.com/nickcolley/jest-axe/issues/92

**Comment by dominicfraser** [comment]
I've had a look through the changes and nothing jumps out at me.

I also used `npm link` and ran my local version with changes in one of our repos and the 46 `jest-axe` tests passed as before - not conclusive but a good sign.

**Comment by nickcolley** [comment]
Just realised the ^ (hat) symbol on our package.json means 3.5.5 is installed by our users anyway, so this is fine to merge and it's what is installed regardless.

**Comment by dominicfraser** [comment]
Thanks Nick :)

**Comment by dominicfraser** [comment]
I'll keep an eye for the release to update our repos :)

**Pull request merged**
